#+OPTIONS: toc:nil ^:nil

* About 51colinux

51colinux is a configured colinux appending some handy features:
 - easier using
 - A optimize image of ubuntu 12.04
 - A configure with no image running
 - No Install, portable colinux. 
 - Run quickly with images(no more than 10 second)
 - Two running mode: 
   1. Windows Service
   2. Application Starting In Tray

Tested support OS: 
 - Windows XP 32bit
 - Windows 7 32bit

Project address is [[https://github.com/wuyao721/51colinux][here]] without os image. 

The os image is too large for github. You can download the whole 51colinux [[http://pan.baidu.com/s/1pKgKwTP][here]] with a optimize ubuntu 12.04 image. 


* Usage

** Running Without Image
colinux can runing without os image but a linux kernel and a simple shell. Running it follow there steps: 
 1. download the project
 2. copy *conf/noimage.conf* to *conf/colinux.conf*
 3. double click *run_portable_colinux.bat* to start colinux, app will be minimal in tray.
 

** Ubuntu 12.04 Image
Currently this project can only support a ubuntu 12.04 image. Running it follow there steps: 
 1. download ubuntu 12.04 image *ubuntu-12.04.vdi* to directory *images* 
 2. copy *conf/ubuntu-12.04.conf* to *conf/colinux.conf*
 3. running as windows service or as application
 4. tty login or ssh login

more information in document *image-ubuntu-12.04* 


* Two Running Mode

** Running in Windows Service
Install service by double click file *colinux-install-service.bat* .

after the service start, login the guest os by ssh client.

Remove service by double click file *colinux-remove-service.bat* .


** Running As App In Tray
Start colinux by double click file *run_portable_colinux.bat* .

The application will minimal in tray. Left click in mouse can restore application window.

TTY Login in application window or ssh login in a ssh tool, eg putty.
